services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: "TaxApiDB"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password"
    ports:
      - "7777:1433"
    volumes:
      - db_data:/var/opt/mssql
  taxapibackend:
    build:
      context: .
    depends_on: 
      - sqlserver
    ports:
      - "7778:8080"

volumes:
  db_data: